# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fruit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_modelTraining = QtWidgets.QPushButton(Dialog)
        self.pushButton_modelTraining.setObjectName("pushButton_modelTraining")
        self.gridLayout.addWidget(self.pushButton_modelTraining, 0, 1, 1, 1)
        self.pushButton_maturitySorting = QtWidgets.QPushButton(Dialog)
        self.pushButton_maturitySorting.setObjectName("pushButton_maturitySorting")
        self.gridLayout.addWidget(self.pushButton_maturitySorting, 1, 1, 1, 1)
        self.pushButton_startSorting = QtWidgets.QPushButton(Dialog)
        self.pushButton_startSorting.setObjectName("pushButton_startSorting")
        self.gridLayout.addWidget(self.pushButton_startSorting, 2, 1, 1, 1)
        self.label_lb = QtWidgets.QLabel(Dialog)
        self.label_lb.setObjectName("label_lb")
        self.gridLayout.addWidget(self.label_lb, 3, 1, 1, 1)
        self.label_picture = QtWidgets.QLabel(Dialog)
        self.label_picture.setObjectName("label_picture")
        self.gridLayout.addWidget(self.label_picture, 0, 0, 4, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_modelTraining.setText(_translate("Dialog", "模型训练"))
        self.pushButton_maturitySorting.setText(_translate("Dialog", "成熟度检测"))
        self.pushButton_startSorting.setText(_translate("Dialog", "开始分拣"))
        self.label_lb.setText(_translate("Dialog", "显示类别"))
        self.label_picture.setText(_translate("Dialog", "显示图片"))
